# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/user/documents/GitHub/SCS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/user/documents/GitHub/SCS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/user/documents/GitHub/SCS/CMakeFiles /Users/user/documents/GitHub/SCS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/user/documents/GitHub/SCS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TGEN

# Build rule for target.
TGEN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TGEN
.PHONY : TGEN

# fast build rule for target.
TGEN/fast:
	$(MAKE) -f CMakeFiles/TGEN.dir/build.make CMakeFiles/TGEN.dir/build
.PHONY : TGEN/fast

#=============================================================================
# Target rules for targets named SCS

# Build rule for target.
SCS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SCS
.PHONY : SCS

# fast build rule for target.
SCS/fast:
	$(MAKE) -f CMakeFiles/SCS.dir/build.make CMakeFiles/SCS.dir/build
.PHONY : SCS/fast

lcs_scorer.o: lcs_scorer.cpp.o

.PHONY : lcs_scorer.o

# target to build an object file
lcs_scorer.cpp.o:
	$(MAKE) -f CMakeFiles/SCS.dir/build.make CMakeFiles/SCS.dir/lcs_scorer.cpp.o
.PHONY : lcs_scorer.cpp.o

lcs_scorer.i: lcs_scorer.cpp.i

.PHONY : lcs_scorer.i

# target to preprocess a source file
lcs_scorer.cpp.i:
	$(MAKE) -f CMakeFiles/SCS.dir/build.make CMakeFiles/SCS.dir/lcs_scorer.cpp.i
.PHONY : lcs_scorer.cpp.i

lcs_scorer.s: lcs_scorer.cpp.s

.PHONY : lcs_scorer.s

# target to generate assembly for a file
lcs_scorer.cpp.s:
	$(MAKE) -f CMakeFiles/SCS.dir/build.make CMakeFiles/SCS.dir/lcs_scorer.cpp.s
.PHONY : lcs_scorer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SCS.dir/build.make CMakeFiles/SCS.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SCS.dir/build.make CMakeFiles/SCS.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SCS.dir/build.make CMakeFiles/SCS.dir/main.cpp.s
.PHONY : main.cpp.s

testgen.o: testgen.cpp.o

.PHONY : testgen.o

# target to build an object file
testgen.cpp.o:
	$(MAKE) -f CMakeFiles/TGEN.dir/build.make CMakeFiles/TGEN.dir/testgen.cpp.o
.PHONY : testgen.cpp.o

testgen.i: testgen.cpp.i

.PHONY : testgen.i

# target to preprocess a source file
testgen.cpp.i:
	$(MAKE) -f CMakeFiles/TGEN.dir/build.make CMakeFiles/TGEN.dir/testgen.cpp.i
.PHONY : testgen.cpp.i

testgen.s: testgen.cpp.s

.PHONY : testgen.s

# target to generate assembly for a file
testgen.cpp.s:
	$(MAKE) -f CMakeFiles/TGEN.dir/build.make CMakeFiles/TGEN.dir/testgen.cpp.s
.PHONY : testgen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TGEN"
	@echo "... SCS"
	@echo "... lcs_scorer.o"
	@echo "... lcs_scorer.i"
	@echo "... lcs_scorer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... testgen.o"
	@echo "... testgen.i"
	@echo "... testgen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

